apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjci1jbi1iZWlqaW5nLml2b2xjZXMuY29tIjp7InVzZXJuYW1lIjoicGFhcy1zYS1kZW1vQDEwMDE5MzIiLCJwYXNzd29yZCI6IlB3ZDEyMzQ1NiIsImF1dGgiOiJjR0ZoY3kxellTMWtaVzF2UURFd01ERTVNekk2VUhka01USXpORFUyIn19fQ==
kind: Secret
metadata:
  name: devops-demo-cr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-deploy
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: devops-demo-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-demo-deploy
    spec:
      containers:
      - image: cr-cn-beijing.ivolces.com/dontdelete/devops-demo:latest-20211028102431
        imagePullPolicy: IfNotPresent
        name: test
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: devops-demo-cr-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
